export { VFileMessage } from 'vfile-message';
export * from './agent-registry/index.ts';
// Bridge — observer/CRDT-bridge shared utilities (precedent #14)
export {
  addsBlankLines,
  applyFastDiff,
  applyIncrementalDiff,
  applyPatchToFm,
  applyPathDeleteToFm,
  applyPathRenameToFm,
  applyPathReorderSeqToFm,
  applyPathReorderToFm,
  applyPathSetToFm,
  applyRenameToFm,
  applyReorderToFm,
  assertContentPreservation,
  BRIDGE_LINE_KINDS,
  BRIDGE_TOLERANCE_CLASSES,
  type BridgeComposition,
  type BridgeDivergenceLocation,
  type BridgeInvariantLogPayload,
  type BridgeInvariantSite,
  type BridgeInvariantViolation,
  BridgeInvariantViolationError,
  type BridgeLineKind,
  BridgeMergeContentLossError,
  type BridgeMergeContentLossInfo,
  type BridgeMergeContentLossLogPayload,
  type BridgeMergeContentLossSide,
  type BridgeMergeContentLossWhich,
  type BridgeToleranceClass,
  type BridgeToleranceSignal,
  bindFrontmatterDoc,
  bodyEdgeEmpties,
  type ComparePmStructuralOptions,
  type ComposeAdjustment,
  classifyBridgeLine,
  classifySeverity,
  comparePmStructural,
  compareRoundTripStructural,
  composeWithDerivedBody,
  composeWithDerivedFrontmatter,
  createMergeBoundarySpace,
  createStructuralFreshnessChecker,
  type DiffChange,
  DUPLICATION_GATE_MIN_LINE_LENGTH,
  defaultScheduler,
  detectAppliedToleranceClasses,
  detectFmRegion,
  diffLinesFast,
  docEdgeRunsDiffer,
  emitToleranceFire,
  type FmBoundarySlotSplit,
  type FmEditError,
  type FmEditResult,
  FORM_WRITE_ORIGIN,
  type FrontmatterBinding,
  type FrontmatterBindingPatchResult,
  type FrontmatterBindingPatchSuccess,
  type FrontmatterBindingPathResult,
  type FrontmatterBindingPathSuccess,
  type FrontmatterBindingRenameResult,
  type FrontmatterBindingRenameSuccess,
  type FrontmatterBindingReorderResult,
  type FrontmatterBindingReorderSuccess,
  type FrontmatterBindingUnsubscribe,
  type FrontmatterDocProvider,
  type FrontmatterSnapshot,
  findDroppedContent,
  findFirstDivergenceIndex,
  fnv1aDigest,
  fragmentHoldsPendingContent,
  type InvariantViolation,
  isParseEquivalentBridge,
  locateBridgeDivergence,
  MAX_FM_REGION_BYTES,
  type MergeBoundarySpace,
  mergeThreeWay,
  normalizeBridge,
  overMultipliedBodyLines,
  PARSE_EQUIVALENCE_TOLERANCE,
  type ParsedFmRegion,
  type PmStructuralNode,
  parseFencedFmRegion,
  parseFmRegion,
  pendingContentLines,
  readFmKeys,
  readFmMap,
  readFmRegionWithError,
  type Scheduler,
  type StructuralDegradeLabel,
  type StructuralDivergenceReason,
  type StructuralEquivalenceResult,
  type StructuralFreshnessChecker,
  type StructuralFreshnessCheckerOptions,
  type SynthesisedConflictMarkers,
  type SynthesisedConflictRegion,
  setToleranceTelemetryHook,
  splitFmBoundarySlot,
  structuralDivergence,
  synthesiseConflictMarkers,
  synthesiseConflictMarkersWithRegions,
  type ToleranceClassSeverity,
  type ToleranceFireRecord,
  type ToleranceTelemetryHook,
  toBridgeInvariantLog,
  tryLineLevelCombine,
} from './bridge/index.ts';

export {
  clampToCodeUnits,
  isBlankNoteContent,
  mapControlCharactersToSpace,
  stripInvisibleCharacters,
} from './bug-report-sidecar/note-content.ts';
export {
  isKnownReportSidecarState,
  isReportIdShape,
  normalizeReportSidecarState,
  REPORT_ID_PATTERN,
  REPORT_SENT_MARKER_SCHEMA_VERSION,
  REPORT_SENT_MARKER_SUFFIX,
  REPORT_SIDECAR_BUNDLE_DIR,
  REPORT_SIDECAR_SCHEMA_VERSION,
  REPORT_SIDECAR_STATES,
  type ReportSentMarker,
  ReportSentMarkerSchema,
  type ReportSidecar,
  type ReportSidecarAttempt,
  type ReportSidecarKnownState,
  ReportSidecarSchema,
  type ReportSidecarState,
} from './bug-report-sidecar/schema.ts';
export {
  type Burst,
  bucketIntoBursts,
  type HumanEdit,
  type SessionTransaction,
} from './burst-grouping.ts';
export type {
  AutoConsolidationTrigger,
  CheckpointBundleExposure,
  CheckpointKind,
  CheckpointKindAttributes,
  CheckpointVisibility,
  ParsedCheckpoint,
} from './checkpoint-kinds.ts';
export {
  CHECKPOINT_KIND_REGISTRY,
  CHECKPOINT_KINDS,
  formatCheckpointBodyLine,
  isSurfacedCheckpointKind,
  parseCheckpoint,
} from './checkpoint-kinds.ts';
export {
  CLIENT_RUNTIME_VERSION_FALLBACK,
  CLIENT_VERSION_HEADER,
  type ClientKind,
  type ClientVersionInput,
  type ClientVersionTokenFields,
  clientVersionHeaders,
  clientVersionTokenFields,
} from './client-version.ts';
export {
  COMMAND_IDENTITIES,
  type CommandAvailabilitySpec,
  type CommandCheckField,
  type CommandContext,
  type CommandGroup,
  type CommandHostScope,
  type CommandIdentity,
  type CommandMenuPlacement,
  type CommandPalettePresence,
  type CommandStateToggle,
  type ContextualTargetKind,
  evaluateCommandAvailability,
  type MenuPlatform,
  type MenuSection,
} from './commands/command-identity.ts';
export { commentLeafText, commentQuoteText } from './comments/leaf-text.ts';
export {
  type ContextMatchOptions,
  contextEvidenceFloor,
  contextMatchScore,
  findAllPassages,
  findPassage,
  type PassageMatch,
  type PassageMatchOptions,
  rewriteCeiling,
} from './comments/passage-match.ts';
export {
  DEFAULT_PULL_INTERVAL_SECONDS,
  DEFAULT_PUSH_INTERVAL_SECONDS,
  isSyncActiveMode,
  isSyncMode,
  MAX_SYNC_INTERVAL_SECONDS,
  MIN_SYNC_INTERVAL_SECONDS,
  modeFromCommittedDefault,
  modeFromLegacyEnabled,
  normalizeStoredMode,
  resolveAutoSyncIntervals,
  resolveEffectiveAutoSyncMode,
  resolveLocalAutoSyncMode,
  STORED_SYNC_ACTIVE_MODES,
  STORED_SYNC_MODES,
  type StoredSyncActiveMode,
  type StoredSyncMode,
  SYNC_ACTIVE_MODES,
  SYNC_INTERVAL_PRESET_SECONDS,
  SYNC_MODE_CHANGE_SOURCES,
  SYNC_MODES,
  type SyncActiveMode,
  type SyncMode,
  type SyncModeChangeSource,
} from './config/auto-sync-mode.ts';
export {
  bindConfigDoc,
  type ConfigBinding,
  type ConfigBindingPatchResult,
  type ConfigBindingPatchSuccess,
  type ConfigDocProvider,
  type Unsubscribe,
} from './config/bind-config-doc.ts';
export {
  type BindOkignoreDocOptions,
  bindOkignoreDoc,
  type OkignoreBinding,
  type OkignoreBindingPatchResult,
  type OkignoreBindingPatchSuccess,
  type OkignoreBindingRejection,
  type OkignoreBindingStatus,
  type OkignoreDocProvider,
  type OkignoreUnsubscribe,
} from './config/bind-okignore-doc.ts';
export {
  type DetectCommittedProjectLocalKeysInput,
  detectCommittedProjectLocalKeys,
  formatIgnoredCommittedKey,
  type IgnoredCommittedKey,
} from './config/committed-scope-diagnostics.ts';
export {
  applyConfigOverlay,
  type EnvConfigLayer,
  type EnvDiagnostic,
  type EnvOverride,
  EnvVarError,
  mechanicalEnvName,
  mechanicalEnvNameTable,
  RECOGNIZED_ENV_VARS,
  resolveEnvConfigLayer,
} from './config/env-layer.ts';
export {
  type ConfigDiagnostic,
  ConfigDiagnosticSchema,
  type ConfigDiagnosticsReport,
  ConfigDiagnosticsReportSchema,
  type ConfigIssue,
  ConfigIssueSchema,
  type ConfigIssueSource,
  ConfigIssueSourceSchema,
  type ConfigValidationError,
  ConfigValidationErrorSchema,
  type FieldScope,
  FieldScopeSchema,
  type ForwardCompatConfigError,
  ForwardCompatConfigErrorSchema,
  humanFormat,
  isKnownConfigError,
  type KnownConfigValidationError,
  KnownConfigValidationErrorSchema,
  type RecoveredConfigDiagnostic,
  type RemovedKeyDiagnostic,
  type ScopedConfigDiagnostic,
  ScopedConfigDiagnosticSchema,
  type ValueFallbackDiagnostic,
  type WriteScope,
  WriteScopeSchema,
} from './config/errors.ts';
export {
  type FieldMeta,
  fieldRegistry,
  getFieldMeta,
  type ReloadClass,
} from './config/field-registry.ts';
export { mergeLayered } from './config/merge-layered.ts';
export {
  type DetectRemovedKeysInput,
  detectRemovedKeys,
  REMOVED_KEYS,
  type RemovedKey,
  stripRemovedKeys,
} from './config/removed-keys.ts';
export {
  DEFAULT_LOOPBACK_IDLE_SHUTDOWN,
  idleShutdownToMs,
  isLoopbackBindAddress,
  isLoopbackOnlyBind,
  requiresExternalConsent,
  resolveServerRuntimeConfig,
  type ServerRuntimeConfig,
} from './config/resolve-server-config.ts';
export type { Err, Ok, Result } from './config/result.ts';
export {
  type Config,
  type ConfigPatch,
  ConfigSchema,
  checkEmbeddingsBaseUrl,
  DEFAULT_EMBEDDINGS_BASE_URL,
  DEFAULT_EMBEDDINGS_DOC_TIMEOUT_MS,
  DEFAULT_EMBEDDINGS_MAX_BATCH_CHARS,
  DEFAULT_EMBEDDINGS_MAX_BATCH_SIZE,
  DEFAULT_EMBEDDINGS_MODEL,
  DEFAULT_LOGS_MAX_BYTES,
  DEFAULT_SERVER_BIND,
  DEFAULT_SPANS_MAX_BYTES,
  DEFAULT_TELEMETRY_ATTRIBUTE_DENYLIST,
  DEFAULT_TUNNEL_PORT,
  IDLE_SHUTDOWN_DURATION_RE,
  isLoopbackEmbeddingsUrl,
  isValidAttachmentFolderPath,
  MAX_EMBEDDINGS_DOC_TIMEOUT_MS,
  MAX_EMBEDDINGS_MAX_BATCH_CHARS,
  MAX_EMBEDDINGS_MAX_BATCH_SIZE,
  MIN_EMBEDDINGS_DOC_TIMEOUT_MS,
  MIN_EMBEDDINGS_MAX_BATCH_CHARS,
  MIN_EMBEDDINGS_MAX_BATCH_SIZE,
  normalizeAttachmentFolderPath,
} from './config/schema.ts';
export { getLeafFieldMeta, resolveLeafSchema } from './config/schema-leaf.ts';
export { CONFIG_SCHEMA_MAJOR, CONFIG_SCHEMA_MAJOR_PATH } from './config/schema-version.ts';
export { type LocateOptions, locateIssue } from './config/source-locator.ts';
export {
  addConfigSpanEvent,
  type ConfigOutcome,
  type ConfigScopeAttr,
  type ConfigSpanAttributes,
  type ConfigTransport,
  type ConfigValidationLayer,
  setConfigOutcome,
  withConfigSpan,
  withConfigSpanSync,
} from './config/telemetry.ts';
export {
  ACTIVITY_TTL_MS,
  changedBlockRange,
  evictStaleEntries,
  FLASH_DEBOUNCE_MS,
  FLASH_DURATION_MS,
  hasNewEntries,
} from './constants/activity.ts';
export {
  CC1_CONTRACT_VERSION,
  CONFIG_DOC_NAME_OKIGNORE,
  CONFIG_DOC_NAME_PROJECT,
  CONFIG_DOC_NAME_PROJECT_LOCAL,
  CONFIG_DOC_NAME_USER,
  CONFIG_DOC_NAMES,
  type ConfigDocName,
  externalSkillFileLiveDocName,
  externalSkillLiveDocName,
  isExternalSkillDocName,
  isManagedArtifactDocName,
  LEGACY_SKILL_STORE_ROOT,
  MANAGED_ARTIFACT_PREFIX_EXTSKILL,
  MANAGED_ARTIFACT_PREFIX_SKILL,
  MANAGED_ARTIFACT_PREFIX_TEMPLATE,
  MANAGED_ARTIFACT_SCOPES,
  type ManagedArtifactScope,
  type ParsedGlobalSkillBundleDoc,
  type ParsedManagedArtifactName,
  type ParsedProjectSkillBundleDoc,
  type ParsedTemplateName,
  parseExternalSkillDocName,
  parseGlobalSkillBundleDoc,
  parseLegacyTemplateDocName,
  parseManagedArtifactName,
  parseProjectSkillBundleDoc,
  parseTemplateContentDocName,
  projectSkillContentDocName,
  resolveSkillBundleWikiTarget,
  resolveSkillSlashTarget,
  SYSTEM_DOC_NAME,
  skillFileLiveDocName,
  skillLiveDocName,
  splitSkillHostQualifier,
  stripMdExt,
  templateContentDocName,
} from './constants/cc1.ts';
export { CHROME_BG_DARK, CHROME_BG_LIGHT } from './constants/chrome.ts';
export {
  CODE_FILE_BARE_NAMES_TO_LANGUAGE,
  CODE_FILE_EXTENSIONS_TO_LANGUAGE,
  codeLanguageForBareFilename,
  codeLanguageForExtension,
  EDITABLE_TEXT_EXTRA_LANGUAGE,
  EDITABLE_TEXT_FILE_EXTENSIONS,
  isEditableTextDocFile,
} from './constants/code-languages.ts';
export type { CreateNewBannerKind } from './constants/create-new-banner.ts';
export {
  CREATE_NEW_PROJECT_FAILURE_REASONS,
  type CreateNewProjectFailureReason,
} from './constants/create-new-project-reason.ts';
export {
  DEFAULT_DOC_EXTENSION,
  type DocExtension,
  SUPPORTED_DOC_EXTENSIONS,
} from './constants/doc-extensions.ts';
export { LINEAGE_EPOCH_KEY } from './constants/doc-lifecycle.ts';
export {
  DOCUMENT_OPEN_BYTE_LIMIT,
  isDocumentOverOpenByteLimit,
  TEXT_DOC_OPEN_BYTE_LIMIT,
} from './constants/document-open.ts';
export {
  ALL_EDITOR_IDS,
  EDITOR_LABELS,
  EDITOR_PROJECT_SKILL_ROOT,
  EDITOR_SETUP_DOC_SLUG,
  EDITOR_USER_SKILL_ROOT,
  type EditorId,
  editorProjectConfigPath,
  HOSTS_WITH_USER_SKILL_DIR,
  HUB_READER_EDITORS,
  PROJECT_SKILL_EDITOR_IDS,
  PROJECT_SKILL_PROJECTION_PATHS,
  piExtensionProjectPath,
  piToolNamespace,
  RESERVED_PROJECT_SKILL_NAME,
  receivesProjectIntegrationWrite,
  STABLE_EDITOR_PROJECT_CONFIG_PATH,
  skillRootActivationPath,
  USER_MCP_GATED_EDITOR_IDS,
  USER_SKILL_EDITOR_IDS,
  USER_SKILL_HOSTS,
} from './constants/editors.ts';
export {
  detectEmbeddedHostFromBrowser,
  type EmbeddedHost,
  UA_PATTERNS,
} from './constants/embedded-host.ts';
export { SHOW_INSTALL_SKILL } from './constants/feature-flags.ts';
export type { OkFolderState } from './constants/folder-state.ts';
export {
  classifyGitHubShareHost,
  credentialHostFromRemoteUrl,
  DEFAULT_GITHUB_OAUTH_CLIENT_ID,
  declaredGitHubHostsFrom,
  GIT_HOST_PROVIDERS,
  type GitHostProvider,
  gitCredentialHostKey,
  isGitCredentialHost,
  isGitHubHost,
  normalizeGitHostname,
} from './constants/github.ts';
export { isOrphanMode, ORPHAN_MODES, type OrphanMode } from './constants/graph.ts';
export {
  ACP_LAUNCH_FAILURE_LOG,
  DEFAULT_SIGTERM_GRACE_MS,
  DEFAULT_SIGTERM_POLL_MS,
  formatSpawnAttemptHeader,
  SERVER_CRASH_LOG,
  SERVER_EXIT_LOG,
  SPAWN_ATTEMPT_MARKER,
  SPAWN_ERROR_LOG,
  SPAWN_ERROR_LOG_MAX_BYTES,
  sliceLastSpawnAttempt,
  spawnErrorLogOpenMode,
} from './constants/lifecycle.ts';
export {
  MANUAL_CHECK_NOTICE_EXPIRY_MS,
  MANUAL_CHECK_WATCHDOG_MS,
} from './constants/manual-update-check.ts';
export {
  GREP_MAX_RESULTS,
  MCP_SERVER_NAME,
  OK_DESKTOP_TERMINAL_ENV,
  OK_HOSTED_AGENT_ENV,
  OPEN_KNOWLEDGE_MCP_TOOLS,
  OPEN_KNOWLEDGE_MCP_WRITE_TOOLS,
  type OpenKnowledgeMcpTool,
  READ_DOCUMENT_HISTORY_DEPTH,
  resolveIsHostedAgent,
  SERVER_TIMEOUT_ERROR_PREFIX,
  SERVER_UNREACHABLE_ERROR_PREFIX,
} from './constants/mcp.ts';
export {
  classifyMcpLauncherEntry,
  DEFAULT_MCP_LAUNCHER_REVISION_CATALOG,
  type FutureMcpLauncherDescriptor,
  type KnownMcpLauncherDescriptor,
  type McpLauncherCapability,
  type McpLauncherClassification,
  type McpLauncherDeclineReason,
  type McpLauncherDescriptor,
  type McpLauncherEnvelope,
  type McpLauncherFamily,
  type McpLauncherRevisionCatalog,
  mcpChainMarkerPrefix,
} from './constants/mcp-launcher.ts';
export {
  MENU_LABELS,
  type MenuLabelKey,
  menuLabelForPlatform,
  OPEN_KNOWLEDGE_DISCORD_URL,
  OPEN_KNOWLEDGE_DOCS_URL,
  OPEN_KNOWLEDGE_GITHUB_URL,
  PLATFORM_MENU_LABELS,
} from './constants/menu-labels.ts';
export {
  NATIVE_MENU_LABELS,
  type NativeMenuLabelKey,
} from './constants/native-menu-labels.ts';
export {
  LOCAL_DIR,
  OK_ACTIVE_MACHINE_LOCAL_ROOT_DIRS,
  OK_DIR,
  OK_LEGACY_MACHINE_LOCAL_ROOT_DIRS,
  OK_MACHINE_LOCAL_ROOT_DIRS,
  OK_MACHINE_LOCAL_ROOT_FILES,
  OK_PROJECT_MARKER,
  OK_USER_HOME_AUTH_FILE,
  OK_USER_HOME_CREDENTIAL_FILES,
  OK_USER_HOME_SECRETS_FILE,
  type OkMachineLocalRootDir,
  type OkMachineLocalRootFile,
  okUserHomeDisplayPath,
  posixOkManagedBinDir,
  SAVED_THEMES_DIRNAME,
  WORKTREES_DIRNAME,
} from './constants/ok-dir.ts';
export {
  pathShimBinDir,
  pathShimBlockLabel,
  pathShimFishConfFileName,
  pathShimHomeDirName,
  pathShimMarkerPath,
} from './constants/path-shim-layout.ts';
export {
  PREVIEW_EMBED_STARTERS,
  type PreviewEmbedStarter,
  previewEmbedFence,
} from './constants/preview-embed-starters.ts';
export {
  PREVIEW_THEME_TOKENS,
  type PreviewThemeToken,
} from './constants/preview-theme-tokens.ts';
export {
  currentDesktopProduct,
  currentMcpServerName,
  DESKTOP_PRODUCTS,
  type DesktopProduct,
  type DesktopProductName,
  desktopChannelLabel,
  desktopWindowsExecutableName,
  desktopWindowsInstallDirNames,
  OK_CHANNEL_ENV,
  PRODUCT_NAME,
  resolveDesktopProductName,
} from './constants/product.ts';
export { isReservedLogDoc } from './constants/reserved-docs.ts';
export { DEFAULT_SERVER_HOST } from './constants/server.ts';
export {
  MACHINE_ID_FILENAME,
  SERVER_AUTHORITY_LEASES_DIRNAME,
  SERVER_AUTHORITY_REGISTRY_FILENAME,
  SHARED_OK_ENTRIES,
  SKILL_MOVE_RETAINED_FILENAME,
  SKILL_PLACEMENTS_FILENAME,
  SKILLS_STORE_DIRNAME,
} from './constants/shared-ok-entries.ts';
export {
  AGENTS_SKILLS_ROOT,
  extractSkillRefs,
  isOpenKnowledgeSkillsSource,
  isSkillRefCandidate,
  OPENKNOWLEDGE_SKILLS_REPO,
  PACK_SKILL_PREFIX,
  RENAMED_PACK_SKILLS,
  rewriteSkillRefs,
  SKILL_REF_RE,
} from './constants/skills.ts';
export {
  isUninstallFeedbackReason,
  UNINSTALL_FEEDBACK_EMAIL_MAX_LEN,
  UNINSTALL_FEEDBACK_NOTE_MAX_LEN,
  UNINSTALL_FEEDBACK_REASONS,
  type UninstallFeedbackReason,
} from './constants/uninstall-feedback.ts';
export {
  ALLOWED_AUDIO_MIME_TYPES,
  ALLOWED_IMAGE_MIME_TYPES,
  ALLOWED_PDF_MIME_TYPES,
  ALLOWED_VIDEO_MIME_TYPES,
  ASSET_EXTENSIONS,
  AUDIO_EXTENSIONS,
  CODE_FILE_EXTENSIONS,
  DEFAULT_ATTACHMENT_FOLDER_PATH,
  DEFAULT_DEDUP_MODE,
  DEFAULT_DEDUP_UI,
  DEFAULT_EMIT_FORMAT,
  type DedupMode,
  type DedupUIMode,
  type EmitFormat,
  EXCALIDRAW_FILE_EXTENSIONS,
  EXECUTABLE_BLOCKLIST_EXTENSIONS,
  FILE_ATTACHMENT_EXTENSIONS,
  IMAGE_EXTENSIONS,
  INLINE_RENDERABLE_EXTENSIONS,
  type InlineAssetMediaKind,
  isExcalidrawDocFile,
  isMarkdownDocFile,
  isMermaidDocFile,
  LINKABLE_ASSET_EXTENSIONS,
  MERMAID_FILE_EXTENSIONS,
  mediaKindForSidebarAssetExtension,
  PDF_EXTENSIONS,
  SANDBOXED_HTML_CSP,
  SANDBOXED_HTML_EXTENSIONS,
  SIDEBAR_AUDIO_ASSET_EXTENSIONS,
  SIDEBAR_IMAGE_ASSET_EXTENSIONS,
  SIDEBAR_PDF_ASSET_EXTENSIONS,
  SIDEBAR_RENDERABLE_ASSET_EXTENSIONS,
  SIDEBAR_TEXT_ASSET_EXTENSIONS,
  SIDEBAR_VIDEO_ASSET_EXTENSIONS,
  TEXT_VIEWER_FALLBACK_EXTENSIONS,
  VIDEO_EXTENSIONS,
  WIKI_EMBED_EXTENSIONS,
} from './constants/upload.ts';
export { CodeBlockFidelity } from './extensions/code-block-fidelity.ts';
export { EmphasisFidelity, StrongFidelity } from './extensions/emphasis-fidelity.ts';
export { EscapeMark } from './extensions/escape-mark.ts';
export { FootnoteDefinition } from './extensions/footnote-definition.ts';
export {
  collectFootnoteIdentifiers,
  FootnoteReference,
  findFootnoteDefinitionInsertPos,
  nextFootnoteIdentifier,
} from './extensions/footnote-reference.ts';
export {
  FM_FENCE_LINE_RE,
  FRONTMATTER_RE,
  prependFrontmatter,
  stripFrontmatter,
  unwrapFrontmatterFences,
} from './extensions/frontmatter.ts';
export { HardBreakFidelity } from './extensions/hard-break-fidelity.ts';
export { HeadingFidelity } from './extensions/heading-fidelity.ts';
export { HtmlBlockFidelity } from './extensions/html-block-fidelity.ts';
export { ImageReferenceFidelity } from './extensions/image-reference-fidelity.ts';
export { ImageSrcFidelity } from './extensions/image-src-fidelity.ts';
export { JsxComponent } from './extensions/jsx-component.ts';
export { JsxInline } from './extensions/jsx-inline.ts';
export { isAllowedLinkUri, LinkFidelity, type LinkStyle } from './extensions/link-fidelity.ts';
export { LinkRefDefFidelity } from './extensions/link-ref-def-fidelity.ts';
export { List, ListItem, ListItemNode, ListNode } from './extensions/list.ts';
export { MathInline } from './extensions/math-inline.ts';
export { RawMdxFallback } from './extensions/raw-mdx-fallback.ts';
export { sharedExtensions } from './extensions/shared.ts';
export { Tag } from './extensions/tag.ts';
export { ThematicBreakFidelity } from './extensions/thematic-break-fidelity.ts';
export {
  getWikiLinkText,
  normalizeNullableString,
  parseWikiLink,
  renderWikiLink,
  WikiLink,
  type WikiLinkAttrs,
} from './extensions/wiki-link.ts';
/**
 * The re-exported attrs are schema-add-only per precedent #9, so this public import path
 * commits to additive evolution only.
 */
export {
  WikiLinkEmbed,
  type WikiLinkEmbedAttrs,
} from './extensions/wiki-link-embed.ts';
export {
  type FrontmatterIssue,
  FrontmatterIssueSchema,
  type FrontmatterValidationError,
  FrontmatterValidationErrorSchema,
  fieldErrorsFromError,
  toFrontmatterIssue,
} from './frontmatter/errors.ts';
export { parseFrontmatterRecord } from './frontmatter/record.ts';
export {
  FRONTMATTER_TYPES,
  type FrontmatterMap,
  FrontmatterMapSchema,
  type FrontmatterPatch,
  FrontmatterPatchSchema,
  type FrontmatterType,
  FrontmatterTypeSchema,
  type FrontmatterValue,
  FrontmatterValueSchema,
  frontmatterValuesEqual,
  inferType,
  isFrontmatterValueEmpty,
  isIsoDateString,
  RESERVED_FRONTMATTER_KEY,
} from './frontmatter/schema.ts';
export {
  extractFrontmatterTags,
  FRONTMATTER_TAG_GRAMMAR_HINT,
  FRONTMATTER_TAG_VALUE_RE,
  isValidFrontmatterTagValue,
} from './frontmatter/tags.ts';
export {
  applyPatchToDocument,
  getDocumentKeys,
  type ParsedFrontmatter,
  parseFrontmatterYaml,
  serializeFrontmatterMap,
  withFences,
} from './frontmatter/yaml-codec.ts';
export {
  diffFrontmatter,
  type FrontmatterDelta,
  FrontmatterDeltaSchema,
  type PropertyChange,
} from './frontmatter-diff.ts';
export { parseBranchList } from './git/branch-list-parser.ts';
export {
  agentToolDirs,
  augmentAgentSpawnPath,
  augmentGitSpawnPath,
  type GitSpawnPathOptions,
  wellKnownToolDirs,
} from './git/git-spawn-path.ts';
export { detectMissingGitHelper } from './git/missing-git-helper.ts';
export type {
  WorktreeInventoryAvailability,
  WorktreeInventoryEntry,
  WorktreeInventoryLocation,
  WorktreeInventoryModel,
  WorktreeInventoryOpenRequest,
  WorktreeInventoryOpenResult,
  WorktreeInventoryRequest,
  WorktreeInventoryResult,
} from './git/worktree-inventory-model.ts';
export {
  type BridgeWorktreeEntry,
  parseWorktreeListPorcelain,
} from './git/worktree-list-parser.ts';
export { WORKTREES_PARENT_DIR, worktreeRelativeDir } from './git/worktree-path.ts';
export {
  type BuildWorktreeSelectorModelInput,
  buildWorktreeSelectorModel,
  projectWorktreeCreateResult,
  stripRemotePrefix,
  type WorktreeCreateRequest,
  type WorktreeCreateResult,
  type WorktreeListResult,
  type WorktreeSelectorEntry,
  type WorktreeSelectorModel,
} from './git/worktree-selector-model.ts';
export {
  type Pathspec,
  pathspecArgs,
  stripPathspecMagic,
  toPathspec,
} from './git-pathspec.ts';
export {
  type AssembleHandoffPromptInput,
  assembleHandoffPrompt,
  assertNeverUrnIpcLookup,
  buildClaudeLaunchCommand,
  buildClaudeUrl,
  buildCliLaunchArgString,
  buildCliLaunchCommand,
  buildCodexUrl,
  buildCursorUrl,
  buildStartupInjectionBytes,
  buildWindowsCliLaunch,
  type ComposeSelection,
  type CreateScenario,
  composeAskProjectPrompt,
  composeAskPrompt,
  composeCreatePrompt,
  composeEmptySpacePrompt,
  composeFilePrompt,
  composeFixAllProblemsPrompt,
  composeFolderPrompt,
  composeLintFixPrompt,
  composeSelectionPrompt,
  composeSkillPrompt,
  composeTerminalBareLaunchPrompt,
  composeThreadBareLaunchPrompt,
  composeWindowsShellLaunchArgs,
  type DocContext,
  type HandoffFailureReason,
  type HandoffOutcome,
  type HandoffPayload,
  type HandoffScope,
  type HandoffTarget,
  type InstallState,
  type IpcChannelReason,
  type IpcChannelWithUrn,
  isTerminalLaunchEnvName,
  isWindowsShellFamily,
  isWindowsShellLaunchFailureReason,
  type LintFixPromptInput,
  launchWithoutSupportFile,
  lookupUrnInRegistry,
  OK_GATED_TOOL_NAMES,
  OK_PROJECT_SKILL_POINTER,
  OK_TERMINAL_SURFACE_PREAMBLE,
  OK_THREAD_SURFACE_PREAMBLE,
  type PromptTransport,
  psQuoteArg,
  quoteWindowsShellPath,
  resolveWindowsShellFamily,
  shellSingleQuote,
  startupInjectionFor,
  type TargetData,
  TERMINAL_CLI_IDS,
  TERMINAL_CLIS,
  TERMINAL_INLINE_PROMPT_BUDGET,
  type TerminalCli,
  type TerminalCliInfo,
  type TerminalLaunchCommand,
  terminalLaunchEnvSlots,
  URN_HTTP_ONLY,
  URN_IPC_REGISTRY,
  type UrnIpcLookup,
  WINDOWS_SHELL_FAMILIES,
  type WindowsShellFamily,
  WindowsShellLaunchError,
  type WindowsShellLaunchFailureReason,
  withSkillPointer,
} from './handoff/index.ts';
export { asBcp47Tag, type Bcp47Tag, toBcp47Tags } from './i18n/bcp47.ts';
export {
  type NavigatorLanguages,
  readBrowserLanguages,
} from './i18n/browser-locale-provider.ts';
export { localeDirection, type TextDirection } from './i18n/direction.ts';
export {
  AUTO_DETECTABLE_LOCALES,
  LAYOUT_DEFERRED_LOCALES,
  type LanguagePreference,
  PICKER_LOCALES,
  SUPPORTED_LOCALES,
  type SupportedLocale,
} from './i18n/locales.ts';
export {
  FALLBACK_LOCALE,
  type LocaleResolution,
  type LocaleResolutionInput,
  type LocaleSource,
  resolveLocale,
} from './i18n/resolve-locale.ts';
export {
  emptyInstalledSkills,
  INSTALLED_SKILLS_FILENAME,
  INSTALLED_SKILLS_REL,
  INSTALLED_SKILLS_SCHEMA_VERSION,
  type InstalledSkillEntry,
  InstalledSkillEntrySchema,
  type InstalledSkillScope,
  InstalledSkillScopeSchema,
  type InstalledSkills,
  InstalledSkillsSchema,
  parseInstalledSkills,
} from './installed-skills/schema.ts';
export type {
  BundleManifest,
  BundleRedaction,
  ClassifiedPath,
  Loggable,
  LogLevel,
  LogPayload,
  OkBugReportCrashAckResult,
  OkBugReportCrashDetectedEvent,
  OkBugReportCrashDumpAvailability,
  OkBugReportCreateResult,
  OkBugReportDeleteResult,
  OkBugReportListResult,
  OkBugReportListRow,
  OkBugReportScreenshot,
  OkBugReportSendFallbackReason,
  OkBugReportSendMetadata,
  OkBugReportSendResult,
  OkImageAttachmentContentType,
  ReportBundleLevel,
  ReportBundleSummary,
  SerializedError,
  SerializedErrorTruncation,
} from './logger-types.ts';
export {
  BUG_REPORT_AGENT_CHAT_ZIP_DIR,
  BUG_REPORT_ATTACHMENT_CONTENT_TYPES,
  BUG_REPORT_ATTACHMENT_EXTENSIONS,
  BUG_REPORT_ATTACHMENTS_ZIP_DIR,
  BUG_REPORT_ATTACHMENTS_ZIP_PREFIX,
  BUG_REPORT_CONTACT_EMAIL_MAX_LENGTH,
  BUG_REPORT_SCREENSHOT_ZIP_ENTRY,
  BUG_REPORT_SCREENSHOT_ZIP_NAME,
  isBugReportAgentChatEntry,
  isBugReportAttachmentEntry,
  isBugReportCrashDumpEntry,
  LOG_LEVELS,
  MAX_BUG_REPORT_ATTACHMENTS,
  MAX_BUG_REPORT_ATTACHMENTS_TOTAL_BYTES,
  MINIDUMP_FILE_EXTENSION,
} from './logger-types.ts';
export {
  LOGGER_OWNED_FIELDS,
  mapConsoleLevel,
  parseStructuredConsoleMessage,
  prepareCapturedConsoleMessage,
  RENDERER_LOG_MAX_BATCH_BYTES,
  RENDERER_LOG_MAX_ENTRIES,
  RENDERER_LOG_MAX_MESSAGE_BYTES,
  type RendererLogLevel,
  truncateLogMessage,
} from './logging/renderer-log.ts';
export {
  redactSecrets,
  SECRET_PATTERN_NAMES,
  scrubSecrets,
} from './logging/secret-scrub.ts';
export { selectFenceChar, widenFenceLength } from './markdown/code-fence.ts';
export {
  MIN_CARRIED_LEADING_EMPTIES,
  MIN_CARRIED_TRAILING_EMPTIES,
} from './markdown/doc-edge-blank-runs.ts';
export {
  HTML_MAX_BYTES,
  HtmlPayloadTooLargeError,
  htmlToMdast,
  mdastToMarkdown,
} from './markdown/html-to-mdast.ts';
export { MarkdownManager, type SerializeCallOptions } from './markdown/index.ts';
export {
  type AppliesToPatternSummary,
  type AppliesToSummary,
  AUDIT_EMPTY_SCOPE_WARNING,
  applyFieldConstraint,
  applyTextEdits,
  assertNeverOkfRuleGroupId,
  assertNeverOkfRuleId,
  CANONICAL_SCHEMA_DIALECT_URIS,
  type CompiledAppliesTo,
  canonicalRuleId,
  compileAppliesTo,
  countDiagnosticsBySource,
  DEFAULT_LINKS_VALIDATION,
  DEFAULT_LINTER_CONFIG,
  DEFAULT_MARKDOWNLINT_CONFIG,
  DEFAULT_SCHEMA_DIALECT,
  DEFAULT_SUPPRESS_LOG_LINK_ADVISORIES,
  deriveValidationRunSources,
  displayCategoryForRule,
  emptyFrontmatterSchemaText,
  type FrontmatterFieldConstraint,
  type FrontmatterSchemaDialect,
  FrontmatterSchemaEditError,
  type FrontmatterSchemaMapping,
  type FrontmatterSchemasListSuccess,
  FrontmatterSchemasListSuccessSchema,
  type FrontmatterSchemaWriteRequest,
  FrontmatterSchemaWriteRequestSchema,
  type FrontmatterScope,
  type FrontmatterSlice,
  findRuleConfigEntry,
  findZeroMatchAppliesToPatterns,
  fixDocument,
  fixMarkdownText,
  frontmatterSchemaCompileError,
  type GoverningFrontmatterSchema,
  isAuditEmptyScopeWarning,
  isFrontmatterSchemaAsset,
  isFrontmatterScoped,
  isMarkdownlintJsonConfig,
  isOkfRuleEnabled,
  isReLintFailedWarning,
  isReLintFailureReason,
  isSupportedSchemaDialect,
  isToolManagedSchemaPath,
  LINKS_VALIDATION_SETTINGS,
  LINT_PLUGIN_IDS,
  LINT_PLUGINS,
  type LinksValidationSetting,
  type LintAuditResponse,
  LintAuditResponseSchema,
  type LintConfigResponse,
  LintConfigResponseSchema,
  type LintDiagnostic,
  type LintDocResult,
  LintDocResultSchema,
  type LinterConfig,
  LinterConfigSchema,
  type LintFixRequest,
  LintFixRequestSchema,
  type LintFixResult,
  LintFixResultSchema,
  type LintPlugin,
  type LintPluginFailure,
  type LintPluginFailureReporter,
  type LintPluginId,
  type LintPosition,
  type LintRange,
  type LintSeverity,
  type LintTextEdit,
  type LocalTargetDiagnosticEvidence,
  type LocalTargetKind,
  type LocalTargetResolutionMethod,
  type LocalTargetRole,
  type LocalTargetSourceForm,
  lintDocument,
  MARKDOWNLINT_RULE_CATALOG,
  type MarkdownlintRuleSetting,
  type MarkdownlintRuleSeverity,
  MarkdownlintRuleWriteRequestSchema,
  type MarkdownlintRuleWriteValue,
  type MarkdownlintSlice,
  OKF_FRONTMATTER_REGISTRY,
  OKF_PROJECT_REGISTRY,
  OKF_RULE_GROUPS,
  OKF_RULE_IDS,
  OKF_SCHEMA_DIR,
  type OkfProjectFinding,
  type OkfRuleGroupId,
  type OkfRuleId,
  type OkfRuleToggles,
  type OkfSchemaFile,
  type OkfSlice,
  okfAdvertisedSchemaMappings,
  okfSchemaPathFor,
  type PersistedLinterConfig,
  RE_LINT_FAILED_WARNING_PREFIX,
  RE_LINT_FAILURE_REASONS,
  type ReLintFailure,
  type ReLintFailureReason,
  ReLintFailureSchema,
  type ResolvedFrontmatterSchemaEntry,
  RULE_DISPLAY_CATEGORIES,
  type RuleCatalogEntry,
  type RuleDisplayCategory,
  type RuleOptionSpec,
  type RuleOptionType,
  removeSchemaField,
  renameSchemaField,
  renderOkfSchemaFiles,
  resolveFrontmatterSchemaDialect,
  resolveMarkdownlintConfig,
  runMarkdownlint,
  runOkfFrontmatterRules,
  runOkfProjectRules,
  type SchemaParentPathSegment,
  SUPPORTED_SCHEMA_DIALECTS,
  selectAdvertisedFrontmatterMappings,
  selectApplicableFrontmatterSchemas,
  selectFrontmatterOnlyConfig,
  selectGoverningFrontmatterSchemas,
  selectOkfFrontmatterSchemas,
  summarizeAppliesTo,
  summarizeLintPluginFailures,
  toEffectiveBase,
  VALIDATION_SOURCES,
  type ValidationAuditCountsResponse,
  ValidationAuditCountsResponseSchema,
  type ValidationAuditResponse,
  ValidationAuditResponseSchema,
  type ValidationCountsBySource,
  type ValidationDiagnostic,
  type ValidationDocCounts,
  ValidationDocCountsSchema,
  type ValidationDocResult,
  ValidationDocResultSchema,
  type ValidationRunMode,
  type ValidationSource,
  type ValidationSourceCounts,
  type ValidationSourceKey,
  validationCoverageLines,
  ZERO_SOURCE_COUNTS,
} from './markdown/lint/index.ts';
export { markdownToHtml, mdastToHtml } from './markdown/mdast-to-html.ts';
export {
  isNonRenderingRange,
  type MaskableLine,
  maskNonRenderingContextLines,
  maskNonRenderingContexts,
  skipInlineCode,
} from './markdown/non-rendering-contexts.ts';
export { isMutatingParserReservation } from './markdown/parser-reservations.ts';
export { markdownToPlainText } from './markdown/plain-text.ts';
export { normalizeReferenceLabel } from './markdown/reference-label.ts';
export { normalizeDocRelativeAssetUrl } from './markdown/resolve-image-url.ts';
export {
  isRelativeUrl,
  isSafeUrl,
  SAFE_URL_SCHEME_RE,
  SAFE_URL_SCHEMES,
} from './markdown/safe-url.ts';
export {
  createTagInTextRegex,
  INLINE_TAG_VALUE_RE,
  TAG_IN_TEXT_PATTERN_SOURCE,
} from './markdown/tag-promotion.ts';
export {
  type CleanWikiSegments,
  normalizeWikiSeparatorEscapes,
  rawSegmentOr,
  type WikiSegmentKind,
} from './markdown/wiki-escape.ts';
export {
  getParseHealth,
  incrementBlockFallback,
  incrementBlockGripClickSelectFailed,
  incrementJsxActionAborted,
  incrementJsxArrowNodeSelectFailed,
  incrementJsxAutoConvertFailed,
  incrementJsxAutoConvertSucceeded,
  incrementJsxChromeDeleteFailed,
  incrementJsxKeyboardDeleteFailed,
  incrementJsxMoveFailed,
  incrementJsxPopoverCloseRestoreFailed,
  incrementJsxPropDropped,
  incrementJsxRenderFailure,
  incrementJsxStuckCopyFailed,
  incrementJsxStuckDeleteFailed,
  incrementWholeDocFallback,
  incrementYpsMismatchBlock,
  incrementYpsMismatchInline,
  type JsxNodeAction,
  type ParseHealthMetrics,
  resetParseHealth,
} from './metrics/parse-health.ts';
export { PROTOCOL_VERSION } from './protocol-version.ts';
export {
  builtInComponents,
  type ComponentRegistry,
  createRegistry,
  wildcardMeta,
} from './registry/index.ts';
export { JSX_SRC_REF_TAGS, type JsxSrcRefTagSpec } from './registry/jsx-src-ref-tags.ts';
export {
  type ComponentEntryFull,
  type ComponentEntryLite,
  type ComponentKind,
  type ComponentParam,
  getAgentCanonicalDescriptors,
  getCanonicalDescriptors,
  projectFull,
  projectLite,
} from './registry/projection.ts';
export type {
  ClipboardHastContext,
  JsxComponentMeta,
  PropDef,
  PropDefBase,
  PropDefBoolean,
  PropDefEnum,
  PropDefNumber,
  PropDefReactNode,
  PropDefString,
} from './registry/types.ts';
export {
  type ActivityAgentHeader,
  ActivityAgentHeaderSchema,
  type ActivityBurst,
  ActivityBurstSchema,
  type ActivityFile,
  ActivityFileSchema,
  type AdvisoryWarning,
  AdvisoryWarningSchema,
  AdvisoryWarningsSchema,
  AGENT_WRITE_BATCH_MAX_DOCS,
  type AgentActivitySuccess,
  AgentActivitySuccessSchema,
  type AgentBurstDiffSuccess,
  AgentBurstDiffSuccessSchema,
  AgentEffectEntrySchema,
  type AgentEffectEntryWire,
  AgentEffectsDocSchema,
  type AgentEffectsDocWire,
  AgentIntegrationsAppliedStepSchema,
  type AgentIntegrationsApplyRequest,
  AgentIntegrationsApplyRequestSchema,
  type AgentIntegrationsApplySuccess,
  AgentIntegrationsApplySuccessSchema,
  AgentIntegrationsIntentSchema,
  type AgentIntegrationsIntentWire,
  AgentIntegrationsPlanConflictSchema,
  AgentIntegrationsProbeSchema,
  AgentIntegrationsSnapshotSchema,
  type AgentPatchRequest,
  AgentPatchRequestSchema,
  type AgentPatchSuccess,
  AgentPatchSuccessSchema,
  AgentPresenceEntrySchema,
  type AgentPresenceEntryWire,
  type AgentUndoRequest,
  AgentUndoRequestSchema,
  type AgentUndoSuccess,
  AgentUndoSuccessSchema,
  type AgentWriteBatchEntry,
  AgentWriteBatchEntrySchema,
  type AgentWriteBatchRequest,
  AgentWriteBatchRequestSchema,
  type AgentWriteBatchResult,
  AgentWriteBatchResultSchema,
  type AgentWriteBatchSuccess,
  AgentWriteBatchSuccessSchema,
  type AgentWriteMdRequest,
  AgentWriteMdRequestSchema,
  type AgentWriteMdSuccess,
  AgentWriteMdSuccessSchema,
  type AgentWriteRequest,
  AgentWriteRequestSchema,
  type AgentWriteSuccess,
  AgentWriteSuccessSchema,
  type Anchor,
  type ApiConfigSuccess,
  ApiConfigSuccessSchema,
  assertNeverProblemType,
  assertNeverSemanticProviderErrorReason,
  assertNeverSemanticQueryOutcome,
  assertNeverWriteWarning,
  type BacklinkCountsSuccess,
  BacklinkCountsSuccessSchema,
  type BacklinkEntry,
  BacklinkEntrySchema,
  type BacklinksSuccess,
  BacklinksSuccessSchema,
  type BatchEntryError,
  BatchEntryErrorSchema,
  BROKEN_LINK_REASONS,
  BROKEN_LINK_SUPPRESSION_REASONS,
  type BranchInfoResponse,
  BranchInfoResponseSchema,
  type BrokenLink,
  type BrokenLinkReason,
  BrokenLinkSchema,
  type BrokenLinkSuppression,
  type BrokenLinkSuppressionReason,
  BrokenLinkSuppressionSchema,
  BrokenLinksSchema,
  type CheckoutFailureReason,
  CheckoutFailureReasonSchema,
  type CheckoutRequest,
  CheckoutRequestSchema,
  type CheckoutResponse,
  CheckoutResponseSchema,
  type ClassifiedGitAuthError,
  type ClientLogEntry,
  ClientLogEntrySchema,
  type ClientLogsRequest,
  ClientLogsRequestSchema,
  type ClientLogsSuccess,
  ClientLogsSuccessSchema,
  CONFLICT_KINDS,
  type CommentCountsSuccess,
  CommentCountsSuccessSchema,
  type CommentTarget,
  type CommentThreadMeta,
  CommentThreadMetaSchema,
  CompleteBatchSuccessSchema,
  ConflictEntrySchema,
  type ConflictEntryWire,
  ConflictKindSchema,
  type ConflictKindWire,
  type ContentDivergenceCurrentState,
  ContentDivergenceCurrentStateSchema,
  type ContentDivergenceWarning,
  ContentDivergenceWarningSchema,
  type CreateFolderRequest,
  CreateFolderRequestSchema,
  type CreateFolderSuccess,
  CreateFolderSuccessSchema,
  type CreatePageRequest,
  CreatePageRequestSchema,
  type CreatePageSuccess,
  CreatePageSuccessSchema,
  classifyGitAuthError,
  classifySemanticProviderError,
  containsXmlTag,
  type DeadLinkEntry,
  DeadLinkEntrySchema,
  type DeadLinkSource,
  DeadLinkSourceSchema,
  type DeadLinksSuccess,
  DeadLinksSuccessSchema,
  type DeletePathRequest,
  DeletePathRequestSchema,
  type DeletePathSuccess,
  DeletePathSuccessSchema,
  DeleteSuccessSchema,
  type DiskEditReconciledWarning,
  DiskEditReconciledWarningSchema,
  type DispatchPayload,
  DispatchPayloadSchema,
  type DocumentListEntry,
  DocumentListEntrySchema,
  type DocumentListSuccess,
  DocumentListSuccessSchema,
  type DocumentReadSuccess,
  DocumentReadSuccessSchema,
  type DuplicatePathRequest,
  DuplicatePathRequestSchema,
  type DuplicatePathSuccess,
  DuplicatePathSuccessSchema,
  type EmbedDetection,
  EmbedDetectionSchema,
  type EmbedDetectSuccess,
  EmbedDetectSuccessSchema,
  type EmbeddingsTestFailureReason,
  EmbeddingsTestFailureReasonSchema,
  EmbedProbeEntrySchema,
  type EmbedProbeEntryWire,
  type EmptyRequest,
  EmptyRequestSchema,
  FOLDER_CONFIG_WARNING_CODES,
  type FolderConfigGetSuccess,
  FolderConfigGetSuccessSchema,
  type FolderConfigPutRequest,
  FolderConfigPutRequestSchema,
  type FolderConfigPutSuccess,
  FolderConfigPutSuccessSchema,
  type FolderConfigWarningCode,
  type ForwardLinkDocEntry,
  ForwardLinkDocEntrySchema,
  type ForwardLinkEntry,
  ForwardLinkEntrySchema,
  type ForwardLinkExternalEntry,
  ForwardLinkExternalEntrySchema,
  type ForwardLinkLocalTarget,
  ForwardLinkLocalTargetSchema,
  type ForwardLinksSuccess,
  ForwardLinksSuccessSchema,
  type FrontmatterPatchRequest,
  FrontmatterPatchRequestSchema,
  type FrontmatterPatchSuccess,
  FrontmatterPatchSuccessSchema,
  GIT_STATUS_CODES,
  type GitAuthFailureSubclass,
  type GitHubReferencePreview,
  GitHubReferencePreviewSchema,
  GitHubReferenceRequestSchema,
  type GitHubReferenceResponse,
  GitHubReferenceResponseSchema,
  type GitHubReferenceStatus,
  type GitStatusCode,
  type GitWorktreeEntry,
  GitWorktreeEntrySchema,
  type GitWorktreeOpenTarget,
  type GitWorktreeStatusSuccess,
  GitWorktreeStatusSuccessSchema,
  type HeadingEntry as PageHeadingEntry,
  HeadingEntrySchema as PageHeadingEntrySchema,
  type HistoryEntry,
  HistoryEntrySchema,
  type HistoryShadowContributor,
  HistoryShadowContributorSchema,
  type HistorySuccess,
  HistorySuccessSchema,
  type HistoryVersionSuccess,
  HistoryVersionSuccessSchema,
  type HubEntry,
  HubEntrySchema,
  type HubsSuccess,
  HubsSuccessSchema,
  type InstalledAgentsSuccess,
  InstalledAgentsSuccessSchema,
  type InstallSkillRequest,
  InstallSkillRequestSchema,
  type InstallSkillSuccess,
  InstallSkillSuccessSchema,
  interpretSkillMoveFailure,
  isBranchNotFoundGitError,
  isLoginFixableGitAuthError,
  isSemanticSearchOffered,
  isSkillMoveRetainedDestinationCode,
  isSkillMoveStateCode,
  isSkillRetentionLedgerCode,
  isSkillSourceStateCode,
  isValidBranchName,
  isWriteWarningKind,
  type LifecycleStatus,
  LifecycleStatusSchema,
  type LinkCheckDeferredWarning,
  LinkCheckDeferredWarningSchema,
  type LinkGraphDocNode,
  LinkGraphDocNodeSchema,
  type LinkGraphEdge,
  LinkGraphEdgeSchema,
  type LinkGraphExternalNode,
  LinkGraphExternalNodeSchema,
  type LinkGraphNode,
  LinkGraphNodeSchema,
  type LinkGraphSuccess,
  LinkGraphSuccessSchema,
  type LinkPreviewMetadata,
  LinkPreviewMetadataSchema,
  type LinkPreviewRequest,
  LinkPreviewRequestSchema,
  type LinkPreviewResponse,
  LinkPreviewResponseSchema,
  type LintViolationWarning,
  LintViolationWarningSchema,
  type LocalOpAuthCancelRequest,
  LocalOpAuthCancelRequestSchema,
  type LocalOpAuthEmptySuccess,
  LocalOpAuthEmptySuccessSchema,
  type LocalOpAuthHostRequest,
  LocalOpAuthHostRequestSchema,
  type LocalOpAuthPatRequest,
  LocalOpAuthPatRequestSchema,
  type LocalOpAuthPatSuccess,
  LocalOpAuthPatSuccessSchema,
  type LocalOpAuthSetIdentityRequest,
  LocalOpAuthSetIdentityRequestSchema,
  type LocalOpAuthStatusSuccess,
  LocalOpAuthStatusSuccessSchema,
  type LocalOpAuthTokenRequest,
  LocalOpAuthTokenRequestSchema,
  type LocalOpAuthTokenSuccess,
  LocalOpAuthTokenSuccessSchema,
  type LocalOpCloneRequest,
  LocalOpCloneRequestSchema,
  type LocalOpEmbeddingsMutationSuccess,
  LocalOpEmbeddingsMutationSuccessSchema,
  type LocalOpEmbeddingsSetKeyRequest,
  LocalOpEmbeddingsSetKeyRequestSchema,
  type LocalOpEmbeddingsTestResponse,
  LocalOpEmbeddingsTestResponseSchema,
  type LocalOpOkInitFailureReason,
  LocalOpOkInitFailureReasonSchema,
  type LocalOpOkInitRequest,
  LocalOpOkInitRequestSchema,
  type LocalOpOkInitResponse,
  LocalOpOkInitResponseSchema,
  LocalTargetDiagnosticEvidenceSchema,
  type LocalTargetDiagnosticEvidenceWire,
  type MetricsAgentEffectsSuccess,
  MetricsAgentEffectsSuccessSchema,
  type MetricsAgentPresenceSuccess,
  MetricsAgentPresenceSuccessSchema,
  type MetricsParseHealthSuccess,
  MetricsParseHealthSuccessSchema,
  type MetricsReconciliationSuccess,
  MetricsReconciliationSuccessSchema,
  type MetricsWatcherRecentSuccess,
  MetricsWatcherRecentSuccessSchema,
  normalizeApiWarnings,
  type OrphanEntry,
  OrphanEntrySchema,
  type OrphanHint,
  OrphanHintSchema,
  type OrphansSuccess,
  OrphansSuccessSchema,
  type PageEntry,
  PageEntrySchema,
  type PageHeadingsSuccess,
  PageHeadingsSuccessSchema,
  type PagesSuccess,
  PagesSuccessSchema,
  PrepareBatchSuccessSchema,
  PrepareDispatchSuccessSchema,
  type PrincipalSuccess,
  PrincipalSuccessSchema,
  type ProblemDetails,
  ProblemDetailsSchema,
  type ProblemType,
  ProblemTypeSchema,
  type PropertyPath,
  PULL_OUTCOMES,
  type PullOutcome,
  PullOutcomeSchema,
  PushPermissionSchema,
  type PushPermissionWire,
  QueueSuccessSchema,
  RECONCILE_REASONS,
  REFUSED_SYMLINK_PATHS_CAP,
  RESOLVE_STRATEGIES,
  ReconcileReasonSchema,
  type ReconcileReasonWire,
  type RenamedAssetMapping,
  RenamedAssetMappingSchema,
  type RenamedDocMapping,
  RenamedDocMappingSchema,
  type RenamePathRequest,
  RenamePathRequestSchema,
  type RenamePathSuccess,
  RenamePathSuccessSchema,
  type RenameRewrittenDoc,
  RenameRewrittenDocSchema,
  type RenderWarning,
  RenderWarningSchema,
  type RescueEntryFlat,
  RescueEntryFlatSchema,
  type RescueEntryTimeline,
  RescueEntryTimelineSchema,
  type RescueListSuccess,
  RescueListSuccessSchema,
  ResolveStrategySchema,
  type ResolveStrategyWire,
  type RollbackRequest,
  RollbackRequestSchema,
  type RollbackSuccess,
  RollbackSuccessSchema,
  type SavedThemeDeleteSuccess,
  SavedThemeDeleteSuccessSchema,
  type SavedThemeListEntry,
  SavedThemeListEntrySchema,
  type SavedThemeSaveRequest,
  SavedThemeSaveRequestSchema,
  type SavedThemeSaveSuccess,
  SavedThemeSaveSuccessSchema,
  type SavedThemeScheme,
  SavedThemeSchemeSchema,
  type SavedThemesListSuccess,
  SavedThemesListSuccessSchema,
  type SavedThemeUpdateRequest,
  SavedThemeUpdateRequestSchema,
  type SavedThemeUpdateSuccess,
  SavedThemeUpdateSuccessSchema,
  type SaveVersionRequest,
  SaveVersionRequestSchema,
  type SaveVersionSuccess,
  SaveVersionSuccessSchema,
  type SaveVersionWriter,
  SaveVersionWriterSchema,
  type SearchRequest,
  SearchRequestSchema,
  type SearchResultEntry,
  SearchResultEntrySchema,
  type SearchSemanticStatus,
  SearchSemanticStatusSchema,
  type SearchSource,
  type SearchSuccess,
  SearchSuccessSchema,
  type SeedApplyRequest,
  SeedApplyRequestSchema,
  type SeedApplySuccess,
  SeedApplySuccessSchema,
  type SeedInstallPackSkillRequest,
  SeedInstallPackSkillRequestSchema,
  type SeedInstallPackSkillSuccess,
  SeedInstallPackSkillSuccessSchema,
  type SeedListPacksSuccess,
  SeedListPacksSuccessSchema,
  type SeedPackEntryCounts,
  SeedPackEntryCountsSchema,
  type SeedPackFolderInfo,
  SeedPackFolderInfoSchema,
  type SeedPackInfo,
  SeedPackInfoSchema,
  type SeedPlanSuccess,
  SeedPlanSuccessSchema,
  type SemanticIndexStatus,
  SemanticIndexStatusSchema,
  type SemanticProviderErrorReason,
  SemanticProviderErrorReasonSchema,
  type SemanticProviderFailureOutcome,
  type SemanticQueryOutcome,
  SemanticQueryOutcomeSchema,
  type ServerInfoBoot,
  ServerInfoBootSchema,
  type ServerInfoSuccess,
  ServerInfoSuccessSchema,
  type ShareConstructUrlErrorCode,
  ShareConstructUrlErrorCodeSchema,
  type ShareConstructUrlRequest,
  ShareConstructUrlRequestSchema,
  type ShareConstructUrlResponse,
  ShareConstructUrlResponseSchema,
  type ShareFreshness,
  ShareFreshnessSchema,
  type SharePublishErrorCode,
  SharePublishErrorCodeSchema,
  type SharePublishNameCheckResponse,
  SharePublishNameCheckResponseSchema,
  type SharePublishOwner,
  type SharePublishOwnerKind,
  SharePublishOwnerKindSchema,
  SharePublishOwnerSchema,
  type SharePublishOwnersErrorCode,
  SharePublishOwnersErrorCodeSchema,
  type SharePublishOwnersResponse,
  SharePublishOwnersResponseSchema,
  type SharePublishRequest,
  SharePublishRequestSchema,
  type SharePublishResponse,
  SharePublishResponseSchema,
  type SharePublishVisibility,
  SharePublishVisibilitySchema,
  type ShareTargetStatusRequest,
  ShareTargetStatusRequestSchema,
  type ShareTargetStatusResponse,
  ShareTargetStatusResponseSchema,
  type ShareTargetStatusVerdict,
  ShareTargetStatusVerdictSchema,
  SKILL_AUTHORING_WARNING_CODES,
  SKILL_INSTALL_WARNING_CODES,
  SKILL_MOVE_RETAINED_DESTINATION,
  SKILL_MOVE_STATE_CODES,
  SKILL_NAME_REGEX,
  SKILL_RETENTION_LEDGER_CODES,
  SKILL_SOURCE_STATE_CODES,
  SKILLS_IMPORT_BULK_MAX,
  type SkillAuthoringWarningCode,
  type SkillDeleteSuccess,
  SkillDeleteSuccessSchema,
  type SkillDuplicateRequest,
  SkillDuplicateRequestSchema,
  type SkillDuplicateSuccess,
  SkillDuplicateSuccessSchema,
  type SkillEditExternalRequest,
  SkillEditExternalRequestSchema,
  type SkillEditExternalSuccess,
  SkillEditExternalSuccessSchema,
  type SkillFileDeleteSuccess,
  SkillFileDeleteSuccessSchema,
  type SkillFileGetSuccess,
  SkillFileGetSuccessSchema,
  type SkillFileKind,
  SkillFileKindSchema,
  type SkillFilePutRequest,
  SkillFilePutRequestSchema,
  type SkillFilePutSuccess,
  SkillFilePutSuccessSchema,
  type SkillFileRenameRequest,
  SkillFileRenameRequestSchema,
  type SkillFileRenameSuccess,
  SkillFileRenameSuccessSchema,
  type SkillFolderAction,
  type SkillFolderActionMcp,
  SkillFolderActionMcpSchema,
  SkillFolderActionSchema,
  type SkillFolderLinkPreview,
  SkillFolderLinkPreviewSchema,
  type SkillFrontmatter,
  SkillFrontmatterSchema,
  type SkillGetSuccess,
  SkillGetSuccessSchema,
  type SkillHostIdArg,
  SkillHostIdArgSchema,
  type SkillImportBulkResult,
  SkillImportBulkResultSchema,
  type SkillImportProvenance,
  SkillImportProvenanceSchema,
  type SkillImportRequest,
  SkillImportRequestSchema,
  type SkillImportSuccess,
  SkillImportSuccessSchema,
  type SkillInstallRequest,
  SkillInstallRequestSchema,
  type SkillInstallStateSuccess,
  SkillInstallStateSuccessSchema,
  type SkillInstallSuccess,
  SkillInstallSuccessSchema,
  type SkillInstallTargetState,
  SkillInstallTargetStateSchema,
  type SkillInstallWarningCode,
  type SkillLocationId,
  SkillLocationIdSchema,
  type SkillMoveFailureOutcome,
  type SkillMoveRequest,
  SkillMoveRequestSchema,
  type SkillMoveScopeRequest,
  SkillMoveScopeRequestSchema,
  type SkillMoveScopeSuccess,
  SkillMoveScopeSuccessSchema,
  type SkillMoveStateCode,
  type SkillMoveSuccess,
  SkillMoveSuccessSchema,
  type SkillOrigin,
  SkillOriginSchema,
  type SkillPayload,
  SkillPayloadSchema,
  type SkillPutRequest,
  SkillPutRequestSchema,
  type SkillPutSuccess,
  SkillPutSuccessSchema,
  type SkillReimportBulkResult,
  SkillReimportBulkResultSchema,
  type SkillReimportRequest,
  SkillReimportRequestSchema,
  type SkillReimportSuccess,
  SkillReimportSuccessSchema,
  type SkillRestoreRequest,
  SkillRestoreRequestSchema,
  type SkillRestoreSuccess,
  SkillRestoreSuccessSchema,
  type SkillRetentionLedgerCode,
  type SkillRevertRequest,
  SkillRevertRequestSchema,
  type SkillRevertSuccess,
  SkillRevertSuccessSchema,
  SkillRootPathSchema,
  type SkillScope,
  SkillScopeSchema,
  type SkillSourceStateCode,
  type SkillsImportBulkRequest,
  SkillsImportBulkRequestSchema,
  type SkillsImportBulkSuccess,
  SkillsImportBulkSuccessSchema,
  type SkillsListEntry,
  SkillsListEntrySchema,
  type SkillsListSuccess,
  SkillsListSuccessSchema,
  type SkillsReimportBulkRequest,
  SkillsReimportBulkRequestSchema,
  type SkillsReimportBulkSuccess,
  SkillsReimportBulkSuccessSchema,
  type SkillTargetsGetSuccess,
  SkillTargetsGetSuccessSchema,
  type SkillTargetsPutRequest,
  SkillTargetsPutRequestSchema,
  type SkillTargetsPutSuccess,
  SkillTargetsPutSuccessSchema,
  type SkillTrackInGitRequest,
  SkillTrackInGitRequestSchema,
  type SkillTrackInGitSuccess,
  SkillTrackInGitSuccessSchema,
  type SkillUninstallRequest,
  SkillUninstallRequestSchema,
  type SkillUninstallSuccess,
  SkillUninstallSuccessSchema,
  type SpawnCursorRequest,
  SpawnCursorRequestSchema,
  type SpawnCursorSuccess,
  SpawnCursorSuccessSchema,
  type StreamingProblemEvent,
  StreamingProblemEventSchema,
  type SuggestLinksMention,
  SuggestLinksMentionSchema,
  type SuggestLinksSuccess,
  SuggestLinksSuccessSchema,
  type SuggestLinksTarget,
  SuggestLinksTargetSchema,
  type SummaryResponseField,
  SummaryResponseFieldSchema,
  SYNC_ERROR_CODES,
  type SyncConflictContentSuccess,
  SyncConflictContentSuccessSchema,
  type SyncConflictsSuccess,
  SyncConflictsSuccessSchema,
  type SyncErrorCode,
  SyncErrorCodeSchema,
  SyncModeSchema,
  type SyncModeWire,
  SyncRemoteSchema,
  type SyncRemoteWire,
  type SyncResolveBlockingRequest,
  SyncResolveBlockingRequestSchema,
  type SyncResolveBlockingSuccess,
  SyncResolveBlockingSuccessSchema,
  type SyncResolveConflictRequest,
  SyncResolveConflictRequestSchema,
  type SyncResolveConflictSuccess,
  SyncResolveConflictSuccessSchema,
  SyncStateSchema,
  type SyncStateWire,
  SyncStatusSchema,
  type SyncStatusWire,
  type SyncTriggerRequest,
  SyncTriggerRequestSchema,
  type SyncTriggerSuccess,
  SyncTriggerSuccessSchema,
  semanticProviderErrorBlocks,
  type TagSummaryEntry,
  TagSummaryEntrySchema,
  type TagsDocEntry,
  TagsDocEntrySchema,
  type TagsForNameSuccess,
  TagsForNameSuccessSchema,
  type TagsListSuccess,
  TagsListSuccessSchema,
  TEMPLATE_NAME_REGEX,
  type TemplateDeleteSuccess,
  TemplateDeleteSuccessSchema,
  type TemplateFrontmatter,
  TemplateFrontmatterSchema,
  type TemplateGetSuccess,
  TemplateGetSuccessSchema,
  type TemplateImportRequest,
  TemplateImportRequestSchema,
  type TemplateImportSuccess,
  TemplateImportSuccessSchema,
  type TemplateMoveRequest,
  TemplateMoveRequestSchema,
  type TemplateMoveSuccess,
  TemplateMoveSuccessSchema,
  type TemplatePayload,
  TemplatePayloadSchema,
  type TemplatePutRequest,
  TemplatePutRequestSchema,
  type TemplatePutSuccess,
  TemplatePutSuccessSchema,
  type TemplatesListEntry,
  TemplatesListEntrySchema,
  type TemplatesListSuccess,
  TemplatesListSuccessSchema,
  type TestFlushGitSuccess,
  TestFlushGitSuccessSchema,
  type TestRescanBacklinksSuccess,
  TestRescanBacklinksSuccessSchema,
  type TestRescanFilesSuccess,
  TestRescanFilesSuccessSchema,
  type TestResetSuccess,
  TestResetSuccessSchema,
  ThreadListSuccessSchema,
  type TrashCleanupRequest,
  TrashCleanupRequestSchema,
  type TrashCleanupSuccess,
  TrashCleanupSuccessSchema,
  UNREADABLE_WARNINGS_TEXT,
  type UploadAssetSuccess,
  UploadAssetSuccessSchema,
  type UploadRequest,
  UploadRequestSchema,
  WatcherDecisionEntrySchema,
  type WatcherDecisionEntryWire,
  type WorkspaceSuccess,
  WorkspaceSuccessSchema,
  WRITE_WARNING_KINDS,
  type WriteWarning,
  type WriteWarningKind,
  WriteWarningSchema,
} from './schemas/api/index.ts';
export {
  CC1_CHANNEL_BRANCH_SWITCHED,
  CC1_CHANNEL_CONFIG_IGNORE_NESTED_ERROR,
  CC1_CHANNEL_CONFIG_VALIDATION_REJECTED,
  CC1_CHANNEL_DISK_ACK,
  CC1_CHANNEL_SERVER_INFO,
  type CC1BranchSwitchedPayload,
  CC1BranchSwitchedPayloadSchema,
  type CC1Channel,
  type CC1ConfigIgnoreNestedErrorPayload,
  CC1ConfigIgnoreNestedErrorPayloadSchema,
  type CC1ConfigValidationRejectedPayload,
  CC1ConfigValidationRejectedPayloadSchema,
  type CC1DerivedViewPayload,
  CC1DerivedViewPayloadSchema,
  type CC1DiskAckPayload,
  CC1DiskAckPayloadSchema,
  type CC1ServerInfoPayload,
  CC1ServerInfoPayloadSchema,
  type DerivedViewChannel,
  DerivedViewChannelSchema,
} from './schemas/cc1.ts';
export {
  createWorkspaceSearchCorpus,
  createWorkspaceSearchDocument,
  DEFAULT_RRF_K,
  DEFAULT_VECTOR_CANDIDATE_LIMIT,
  DEFAULT_VECTOR_SIMILARITY_FLOOR,
  DEFAULT_WORKSPACE_SEARCH_LIMIT,
  MAX_WORKSPACE_SEARCH_LIMIT,
  searchWorkspaceCorpus,
  searchWorkspaceDocuments,
  updateWorkspaceSearchCorpus,
  type WorkspaceSearchCorpus,
  type WorkspaceSearchCorpusUpdate,
  type WorkspaceSearchDocument,
  type WorkspaceSearchIntent,
  type WorkspaceSearchKind,
  type WorkspaceSearchOptions,
  type WorkspaceSearchRanking,
  type WorkspaceSearchRebuildReason,
  type WorkspaceSearchResult,
  type WorkspaceSearchScope,
  type WorkspaceSemanticInput,
  workspaceSearchBasename,
  workspaceSearchPathSegments,
} from './search/workspace-search.ts';
export { planHasOutstandingWork, type SeedPlanWorkShape } from './seed-plan-work.ts';
export {
  type BranchMatchOutcome,
  type Candidate,
  type CandidateBridgeDeps,
  type CandidateSelection,
  type CandidateSelectionPayload,
  type CanonicalGitHubShareSource,
  canonicalGitHubRemoteUrl,
  classifyBranchMatch,
  type DecodedShare,
  type DecodedShareV1,
  type DecodedShareV2,
  decodeShareUrl,
  type ExpectedShareRepo,
  encodeShareUrl,
  findRecentProjectsForRepo,
  type HeadBranchInfo,
  InvalidShareUrlError,
  isGitWorkingTree,
  MAX_V2_SHARE_PAYLOAD_BYTES,
  MAX_V2_SHARE_TOKEN_CHARS,
  MAX_V2_SHARED_URL_UTF8_BYTES,
  parseCanonicalGitHubShareUrl,
  projectCanonicalGitHubShareTarget,
  type RecentProjectEntry,
  type ResolvedGitDirKind,
  selectCandidate,
  serializeCanonicalGitHubShareUrl,
  UnsupportedShareVersionError,
} from './sharing/index.ts';
export {
  emptySkillState,
  resolveBundleEnabled,
  SKILL_STATE_FILENAME,
  SKILL_STATE_SCHEMA_VERSION,
  SKILL_STATE_SURFACES,
  SKILL_STATE_TARGETS,
  SKILL_STATE_VERSION_RE,
  type SkillState,
  type SkillStateBundleEntry,
  SkillStateSchema,
  type SkillStateSurface,
  type SkillStateTarget,
  type SkillStateTargetEntry,
} from './skill-state/schema.ts';
export {
  isSkillInstallTarget,
  type SkillInstallTarget,
  type SkillTargetEditor,
  SkillTargetEditorSchema,
  type SkillUserTargetEditor,
  SkillUserTargetEditorSchema,
} from './skill-targets/schema.ts';
export {
  SKILL_IMPORT_MAX_BUNDLE_FILES,
  SKILL_IMPORT_MAX_FILE_BYTES,
  SKILL_IMPORT_MAX_TOTAL_BYTES,
} from './skills-catalog/import-limits.ts';
export {
  type PluginUpstream,
  pluginUpstreamsByName,
} from './skills-catalog/plugin-upstream.ts';
export {
  type CatalogSkill,
  CatalogSkillSchema,
  OK_PACK_SCHEMA_VERSION,
  type OkPack,
  OkPackSchema,
  type PluginBundleMetadata,
  PluginBundleMetadataSchema,
  type PluginSourceMetadata,
  PluginSourceMetadataSchema,
  type SkillDetail,
  SkillDetailSchema,
  type SkillDiscover,
  SkillDiscoverSchema,
  type SkillInert,
  SkillInertSchema,
  type SkillManifest,
  SkillManifestSchema,
  type SkillPreview,
  SkillPreviewSchema,
  type SkillProvenance,
  SkillProvenanceSchema,
  type SkillRefResolution,
  SkillRefResolutionSchema,
  type SkillSearchResult,
  SkillSearchResultSchema,
  type SkillsInstalledSuccess,
  SkillsInstalledSuccessSchema,
  type SkillsSearchSuccess,
  SkillsSearchSuccessSchema,
} from './skills-catalog/schema.ts';
export {
  catalogRawScopeToOkScope,
  isDetectedSkillInProject,
  isSkillOutsideOpenProject,
} from './skills-catalog/scope.ts';
export {
  ALWAYS_ON_TOKEN_BUDGET,
  estimateSkillCost,
  ON_TRIGGER_TOKEN_BUDGET,
  READABLE_SKILL_EXTENSIONS,
  type SkillCostInput,
  type SkillCostTiers,
  SkillCostTiersSchema,
} from './skills-catalog/skill-cost.ts';
export {
  isLocalSkillSource,
  parseSkillsShCatalogSource,
  type SkillsShCatalogSource,
  type SkillsShSkillLinks,
  skillsShSkillLinks,
} from './skills-catalog/source-fields.ts';
export { SYNC_PAUSED_REASONS, type SyncPausedReason } from './sync-paused-reason.ts';
export {
  composeTemplateFile,
  instantiateDoc,
  parseTemplateFile,
  TEMPLATE_IDENTITY_KEY,
  type TemplateIdentity,
  type TemplateModel,
} from './templates/template-format.ts';
export {
  DEFAULT_TERMINAL_PLACEMENT,
  MIN_TERMINAL_RIGHT_WIDTH,
  normalizeTerminalPlacement,
  normalizeTerminalRightWidth,
  PREFERRED_TERMINAL_RIGHT_WIDTH,
  RIGHT_TERMINAL_CELL_WIDTH_PX,
  RIGHT_TERMINAL_CHROME_WIDTH_PX,
  RIGHT_TERMINAL_MIN_COLUMNS,
  RIGHT_TERMINAL_PREFERRED_COLUMNS,
  TERMINAL_PLACEMENTS,
  type TerminalPlacement,
} from './terminal-layout.ts';
export type {
  AnsiSlotName,
  Base16Palette,
  Base16ParseError,
  Base16ParseResult,
  Base16Scheme,
  Base16Slot,
} from './theme/base16.ts';
export {
  BASE16_SLOT_ROLES,
  BASE16_SLOTS,
  base16ToTokens,
  base16ToYaml,
  isBase16Hex,
  mixHex,
  parseBase16Scheme,
  relativeLuminance,
} from './theme/base16.ts';
export type {
  ColorThemeSelection,
  ColorThemeSelectionInput,
  SavedThemeIdError,
  SavedThemeIdResult,
  SavedThemeNameResult,
  ThemePlugin,
  ThemePluginId,
} from './theme/theme-plugins.ts';
export {
  colorThemeMode,
  deriveSavedThemeId,
  deriveSavedThemeName,
  generateColorThemesCss,
  isDarkTheme,
  parseSavedThemeId,
  renderThemeBlock,
  resolveColorThemeSelection,
  resolveModePreference,
  resolveThemePlugin,
  SAVED_THEME_ID_PREFIX,
  THEME_ID_PATTERN,
  THEME_PLUGIN_IDS,
  THEME_PLUGINS,
} from './theme/theme-plugins.ts';
export type { Actor, PrincipalId, SessionId } from './types/actor.ts';
export type {
  AgentFlashEntry,
  AgentFocusEntry,
  AgentPresenceEntry,
  AwarenessState,
  AwarenessUser,
} from './types/awareness.ts';
export {
  AGENT_THREAD_SENTINEL_DOC,
  CONNECTED_SENTINEL_DOC,
  isPresenceSentinelDocName,
} from './types/awareness.ts';
export type { Identity } from './types/identity.ts';
export type { Principal } from './types/principal.ts';
export type {
  EntryType,
  ShadowContributor,
  TimelineEntry,
} from './types/timeline.ts';
export type {
  OkUninstallBridge,
  UninstallDispatchRequest,
  UninstallDispatchResult,
  UninstallIntent,
  UninstallNoticeChecklistItem,
  UninstallNoticeScreen,
  UninstallProjectRow,
  UninstallScreenSpec,
} from './uninstall-bridge.ts';
export { UNINSTALL_RESULT_WAIT_TIMEOUT_MS } from './uninstall-bridge.ts';
export {
  HIDDEN_CONFIG_BASENAMES,
  isHiddenDocName,
  isProjectSkillBundlePath,
  isValidDocName,
  validateDocName,
} from './util/doc-name.ts';
export { applyByPrefixSuffix } from './utils/apply-by-prefix-suffix.ts';
export { toDesktopAssetHref } from './utils/asset-href.ts';
export { ChunkedInsertError, chunkedYTextInsert } from './utils/chunked-insert.ts';
export { createCodeFenceTracker } from './utils/code-fence-tracker.ts';
export { isEmbedUrlRewritable, rewriteEmbedUrl } from './utils/embed-url-rewrite.ts';
export { extensionOf } from './utils/extension.ts';
export { formatFileSize } from './utils/file-size.ts';
export { getGitHubStars } from './utils/github-stars.ts';
export { scanHeadingLine } from './utils/heading-scan.ts';
export {
  AGENT_COLORS,
  AGENT_ICON_COLORS,
  AGENT_ICON_COLORS_DARK,
  colorFromSeed,
  computeInitials,
  deriveIconColor,
  displayNameFromClientName,
  formatPresenceLabel,
  generateRandomColor,
  generateRandomName,
  getIdentity,
  HUMAN_COLORS,
  iconFromClientName,
  SYSTEM_WRITER_DISPLAY_NAMES,
} from './utils/identity.ts';
export {
  type AnchorLinkTarget,
  type AssetLinkTarget,
  assertNeverLinkTarget,
  buildAbsoluteMarkdownHref,
  buildRelativeMarkdownHref,
  type ClassifiedLinkTarget,
  classifyMarkdownHref,
  classifyWikiLinkTarget,
  type DocLinkTarget,
  type ExternalLinkTarget,
  extractAssetExtension,
  isExternalHref,
  type ResolveAssetProjectPathOptions,
  resolveAssetProjectPath,
} from './utils/link-targets.ts';
export {
  isLoomUrl,
  type ParsedLoomUrl,
  parseLoomUrl,
} from './utils/loom-embed.ts';
export { type BasenameIndex, createBasenameIndex } from './utils/path-resolve.ts';
export { type PdfAnchorParts, parsePdfAnchor } from './utils/pdf-anchor.ts';
export { randomUUID } from './utils/random-uuid.ts';
export { formatRelativeAge, RELATIVE_TIME_UNKNOWN } from './utils/relative-time.ts';
export {
  decodeHrefPath,
  encodeHrefPath,
  encodeHrefPathSegment,
  type ResolvedInternalHref,
  resolveInternalHref,
} from './utils/resolve-internal-href.ts';
export { sanitizeFolderName } from './utils/sanitize-folder-name.ts';
export { sleep } from './utils/sleep.ts';
export {
  disambiguateSlug,
  getHeadingSlug,
  type HeadingEntry,
  toWikiLinkSlug,
  wikiLinkHref,
} from './utils/slug.ts';
export { expandTagToHierarchy, tagsMatchingPrefix } from './utils/tag-rollup.ts';
export {
  type DependencySlug,
  dependencySlug,
  type IdentityKey,
  identityKey,
  leafKey,
  TARGET_IDENTITY,
  type TargetKind,
  wikiAssetPathKey,
} from './utils/target-identity.ts';
export {
  addDocumentFolders,
  asTargetNamespace,
  createTargetNamespace,
  isTargetNamespace,
  type MutableTargetNamespace,
  resolveName,
  type TargetMatch,
  type TargetNamespace,
} from './utils/target-namespace.ts';
export {
  hasUninstallFeedbackContent,
  type PostUninstallFeedbackOptions,
  postUninstallFeedback,
  type UninstallFeedbackAnswers,
  type UninstallFeedbackResult,
  type UninstallFeedbackSource,
  type UninstallFeedbackSubmission,
} from './utils/uninstall-feedback-submit.ts';
export { isVimeoUrl } from './utils/vimeo-embed.ts';
export {
  buildPagesByBasenameIndex,
  buildPagesBySlugIndex,
  buildWikiLinkAssetTargetKeys,
  createWikiAssetResolver,
  getWikiLinkResolutionCandidates,
  isResolvedWikiLinkTarget,
  resolveWikiLinkAssetTarget,
  resolveWikiLinkTarget,
  resolveWikiLinkTargetDocName,
  type WikiLinkLookupIndex,
  type WikiLinkPagesInput,
} from './utils/wiki-link-resolve.ts';
export {
  type ParsedYouTubeUrl,
  parseYouTubeUrl,
  youtubeEmbedUrl,
} from './utils/youtube-embed.ts';
