export const NESTED_RUN_DEADLINE_MS = 35_000;
export const NESTED_RUN_STOP_GRACE_MS = 5_000;
const NESTED_RUN_RESULT_MARGIN_MS = 5_000;

export const NESTED_RUN_TIMEOUT_MS =
  NESTED_RUN_DEADLINE_MS + NESTED_RUN_STOP_GRACE_MS + NESTED_RUN_RESULT_MARGIN_MS;
